### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Rizean** [NickNo-dev/LP-Mods#1]
# Errors
## nn_PornEmpire\Scenes\nn_pe_scene_do_shooting_new.lpscene
* [ ] LINE: 275  WARN: UNKNOWN_SYNTAX - ModelmoveToPersonStand(Player, 50)
* [ ] check line 417 looks like it should be an elseif -  LINE: 474  ERROR: BLOCK_SCOPE_ERROR - Expected EndIf but found endwhile for If starting on line: 415
* [ ] LINE: 922  WARN: UNKNOWN_SYNTAX - MainActor.moveToPersonStand(Player, 50
## nn_PornEmpire\Scenes\nn_pe_scene_negotiate_shooting_price_main_actor.lpscene
* [ ] LINE: 221  WARN: UNKNOWN_SYNTAX - askingPrice
## nn_PornEmpire\Scenes\nn_pe_scene_rent_office.lpscene
* [ ] check lines 86/87 maybe missing endif? LINE: 110  ERROR: BLOCK_SCOPE_ERROR - Expected EndIf but found endwhile for If starting on line: 85

**Comment by NickNo-dev** [comment]
nn_pe_scene_do_shooting_new.lpscene:
- Line 275 corrected
- Line 417/415/474 not sure. In my current version this already looks correct (attached)
- 922: is correct here as well.

nn_pe_scene_negotiate_shooting_price_main_actor.lpscene:
- This file does not have 221 lines?

nn_pe_scene_rent_office.lpscene
- Don't see a problem. Same as with the 417/415 above.
[nn_PE_DEV.zip](https://github.com/NickNo-dev/LP-Mods/files/5936318/nn_PE_DEV.zip)
